services:
  cms-backend:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - cms-database
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://root:password@cms-database:5432/cmsdb
  cms-database:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cmsdb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
